model:
  target: cldm.tryon_cldm.ControlLDM
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "jpg"
    cond_stage_key: "txt"
    control_key: "hint"
    agnostic_key: "agnostic"
    image_size: 64
    channels: 4
    cond_stage_trainable: True  # set to True due to projection layer
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    only_mid_control: False
    drop_cond_rate: 0.1
    feed_cloth_to_controlnet: False  # consistent with hint_channels

    control_stage_config:
      target: cldm.tryon_cldm.ControlNet
      params:
        image_size: 32 # unused
        in_channels: 9  # z_x:4, z_ag:4, z_ag_m:1
        hint_channels: 3  # openpose:3, cloth:3, cloth_m:1
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    unet_config:
      target: cldm.tryon_cldm.ControlledUnetModel
      params:
        image_size: 32 # unused
        in_channels: 9  # z_x:4, z_ag:4, z_ag_m:1
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPTextImageEmbedder
      params:
        image_layer: "last"  # "last":1024, "projection":768
        use_text: False

train:
  sd_path: "./models/control_sd15_openpose.pth"
  sd_locked: True
  only_mid_control: False
  batch_size: 4
  logger_freq: 150
  learning_rate: 1e-5
  zero_init_input_blocks: True

  dataset_train_config:
    target: ldm.data.tryon_dataset.TryOnDataset
    params:
      root: "/cfs/yuange/datasets/VTON-HD"
      mode: "train"
      reconstruct_rate: 0.
      use_warp_pasted_agnostic: True

